.PHONY: docker_pipelines docker_run_fisher docker_run_drawer

docker_pipelines: docker_run_fisher docker_run_drawer

# Set up the environment to run docker image
# It includes create a run directory, copy run_files for docker to run directory and decompress input data 
env_setup: 
	make create_run_dir copy_run_files_docker decompress_input_data

# Run fisher pipeline
docker_run_fisher:
	docker run -v $(CURDIR)/run_dir:/home/test/run_dir -v $(abspath ../)/data/networks:/home/data/networks -v $(abspath ../)/data/spreadsheets:/home/data/spreadsheets knowengdev/geneset_characterization_pipeline:09_12_2016 /bin/bash -c "cd test; make run_fisher"

# Run DRaWR pipeline
docker_run_drawr:
	docker run -v $(CURDIR)/run_dir:/home/test/run_dir -v $(abspath ../)/data/networks:/home/data/networks -v $(abspath ../)/data/spreadsheets:/home/data/spreadsheets knowengdev/geneset_characterization_pipeline:09_12_2016 /bin/bash -c "cd test; make run_drawr"

