.PHONY: docker_pipelines docker_run_fisher docker_run_drawer

docker_pipelines: docker_run_fisher docker_run_drawer

# Run fisher pipeline
docker_run_fisher:
	docker run -v $(CURDIR)/run_dir:/home/run_dir -v $(abspath ../)/data/networks:/home/data/networks -v $(abspath ../)/data/spreadsheets:/home/data/spreadsheets -it knowengdev/geneset_characterization:09_08_2016 make run_fisher

# Run DRaWR pipeline
docker_run_drawr:
	docker run -v $(CURDIR)/run_dir:/home/run_dir -v $(abspath ../)/data/networks:/home/data/networks -v $(abspath ../)/data/spreadsheets:/home/data/spreadsheets -it knowengdev/geneset_characterization:09_08_2016 make run_drawr

