#.PHONY: run_integration

run_integration:
	PYTHONPATH='/workspace/GeneSet_Characterization_Pipeline/src/' python3 /workspace/GeneSet_Characterization_Pipeline/test/integration/geneset_characterization.py -run_directory /workspace/GeneSet_Characterization_Pipeline/test/integration/results/ -run_file DRaWR_run_file.yml